logging:
  level:
    org:
      hibernate:
        SQL: INFO
server:
  error:
    whitelabel:
      enabled: true
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      connection-timeout: 1200000
      maximum-pool-size: 5
      minimum-idle: 2
      pool-name: data-source
    url: jdbc:mysql://localhost:3306/keyist?useSSL=false&useUnicode=yes&characterEncoding=UTF-8
    username: root
    password: 
  jackson:
    date-format: MMMM dd yyyy / HH:mm
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
  mail:
    host: smtp.gmail.com
    port: 587
    host_address : "http://localhost:4200"
    username: "chaouki.devs@gmail.com"
    password: "vgaoizlpaketeebq"
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
    protocol: smtp
    test-connection: false
    
  mvc:
    throw-exception-if-no-handler-found: true

security:
  public-pattern: /api/public/**
  auth:
    username: user_name
    url: http://localhost:8081/oauth/check_token
    client_id: client_id
    client_password: client_password
    connection_timeout: 60
    read_timeout: 60
    whitelist: >
      /,
      /v2/api-docs,
      /swagger-resources,
      /swagger-resources/**,
      /configuration/ui,
      /configuration/security,
      /swagger-ui.html,
      /webjars/**,
      /api/public/**

swagger:
  host:
    address: localhost:4200
    path: /
  api:
    name: Keyist Api Documentation
    version: v1
  contact:
    name: Ant Kaynak
    url: https://www.keyist.tech
    email: antkaynak1@gmail.com

